=== alfonsoroca/lmsgi-actividad2/biblioteca.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
            Schema para la biblioteca de la Actividad 2
        </xs:documentation>
    </xs:annotation>
    
    <!-- NODO RAIZ - BIBLIOTECA -->
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <!-- NODO DOCUMENTOS (podrían existir otros nodos como empleados o inventario-->
                <xs:element name="documentos">
                    <xs:complexType>
                        <xs:choice minOccurs="0" maxOccurs="unbounded">

                            <!-- LIBRO -->
                            <xs:element name="libro" minOccurs="0" maxOccurs="unbounded"> <!-- 0 o muchos-->
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string"></xs:element>
                                        <xs:element name="capitulo" minOccurs="1" maxOccurs="unbounded"> <!-- 1 o muchos-->
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulo" type="xs:string"></xs:element>
                                                    <xs:element name="contenido"> <!-- Elemento vacio con un atributo-->
                                                        <xs:complexType>
                                                            <xs:attribute name="url" type="xs:anyURI" use="optional"></xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="paginas" type="xs:int" use="required"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="indice" type="xs:string"></xs:element>
                                        <xs:element name="sinopsis" type="xs:string"></xs:element>
                                        <xs:element name="contenido">
                                            <xs:complexType>
                                                <xs:attribute name="url" type="xs:anyURI" use="optional"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <!-- Los atributos se incluyen al final del complexType-->
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:ID">
                                                <!-- Validar el ID para LIBRO -->
                                                <xs:pattern value="L[0-9]{4}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="tipo_clase" use="required"> <!-- Al añadir una restricción hay que quitar el tipo de la declaración-->
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="novela"></xs:enumeration>
                                                <xs:enumeration value="infantil"></xs:enumeration>
                                                <xs:enumeration value="didactico"></xs:enumeration>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="paginas" type="xs:int" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>

                            <!-- REVISTA -->
                            <xs:element name="revista" minOccurs="0" maxOccurs="unbounded"> <!-- 0 o muchos-->
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string"></xs:element>
                                        <xs:element name="numero" type="xs:int"></xs:element>
                                        <xs:element name="indice" type="xs:string"></xs:element>
                                        <xs:element name="secciones"> 
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="seccion" minOccurs="1" maxOccurs="unbounded"> <!-- 1 o muchos-->
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="contenido">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="url" type="xs:anyURI" use="optional"></xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="paginas" type="xs:int" use="required"></xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="contenido">
                                            <xs:complexType>
                                                <xs:attribute name="url" type="xs:anyURI" use="optional"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <!-- Los atributos se incluyen al final del complexType-->
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:ID">
                                                <!-- Validar el ID para REVISTA -->
                                                <xs:pattern value="R[0-9]{4}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="tipo_clase" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="informática"></xs:enumeration>
                                                <xs:enumeration value="corazón"></xs:enumeration>
                                                <xs:enumeration value="coches"></xs:enumeration>
                                                <xs:enumeration value="investigación"></xs:enumeration>
                                                <xs:enumeration value="otras"></xs:enumeration>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="paginas" type="xs:int" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>

                            <!-- PERIODICO -->
                            <xs:element name="periodico" minOccurs="0" maxOccurs="unbounded"> <!-- 0 o muchos-->
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="secciones">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="seccion" minOccurs="1" maxOccurs="unbounded"> <!-- 1 o muchos-->
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="articulo">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="contenido">
                                                                                <xs:complexType>
                                                                                    <xs:attribute name="url" type="xs:anyURI" use="optional"></xs:attribute>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="autor" type="xs:string" use="required"></xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="tipo_sec" use="required">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="económica"></xs:enumeration>
                                                                        <xs:enumeration value="opinión"></xs:enumeration>
                                                                        <xs:enumeration value="deportes"></xs:enumeration>
                                                                        <xs:enumeration value="nacional"></xs:enumeration>
                                                                        <xs:enumeration value="internacional"></xs:enumeration>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>

                                        </xs:element>
                                        <xs:element name="indice" type="xs:string"></xs:element>
                                        <xs:element name="contenido">
                                            <xs:complexType>
                                                <xs:attribute name="url" type="xs:anyURI" use="optional"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <!-- Los atributos se incluyen al final del complexType-->
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:ID">
                                                <!-- Validar el ID para PERIODICO -->
                                                <xs:pattern value="P[0-9]{4}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="tipo_clase" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="nacional"></xs:enumeration>
                                                <xs:enumeration value="internacional"></xs:enumeration>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <!-- La fecha tiene el formato yyyy-mm-dd -->
                                    <xs:attribute name="fecha" type="xs:date" use="required"></xs:attribute> 
                                </xs:complexType>
                            </xs:element>
                        
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alfonsoroca/lmsgi-actividad2/bibliotecaXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Actividad 2 LMSGI - Biblioteca -->

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation= "biblioteca.xsd">
    <documentos>

        <!-- LIBRO -->
        <libro id="L0001" tipo_clase="novela" paginas="100">
            <titulo>El libro gordo de Petete</titulo>
            <capitulo paginas="50">
                <titulo>Capitulo 1</titulo>
                <contenido url="www.contenido.es/id=L0001/cap1"></contenido>
            </capitulo>
            <capitulo paginas="50">
                <titulo>Capitulo 2</titulo>
                <contenido url="www.contenido.es/id=L0001/cap2"></contenido>
            </capitulo>
            <indice>
                <![CDATA[
                    Inicio.............1
                    Final..............2
                ]]>
            </indice>
            <sinopsis>Un libraco gordo</sinopsis>
            <contenido url="www.contenido.es/id=L0001"></contenido>
        </libro>

        <!-- REVISTA -->
        <revista id="R0001" tipo_clase="corazón" paginas="30">
            <titulo>Moneda y Timbre</titulo>
            <numero>654</numero>
            <indice>
                <![CDATA[
                    Inicio.............1
                    Final..............2
                ]]>
            </indice>
            <secciones>
                <seccion paginas="12">
                    <contenido url="www.contenido.es/id=R0001/sec01"></contenido>
                </seccion>
                <seccion paginas="13">
                    <contenido url="www.contenido.es/id=R0001/sec02"></contenido>
                </seccion>
            </secciones>
            <contenido url="www.contenido.es/id=R0001"></contenido>
        </revista>

        <!-- PERIODICO -->
        <periodico id="P0001" tipo_clase="nacional" fecha="1990-11-21"> <!-- La fecha tiene el formato yyyy-mm-dd -->
            <secciones>
                <seccion tipo_sec="económica">
                    <articulo autor="Pedro">
                        <contenido url="www.contenido.es/id=P0001/economica"></contenido>
                    </articulo>
                </seccion>
                <seccion tipo_sec="opinión">
                    <articulo autor="Juan">
                        <contenido url="www.contenido.es/id=P0001/opinion"></contenido>
                    </articulo>
                </seccion>
                <seccion tipo_sec="deportes">
                    <articulo autor="Pablo">
                        <contenido url="www.contenido.es/id=P0001/deportes"></contenido>
                    </articulo>
                </seccion>
                <seccion tipo_sec="nacional">
                    <articulo autor="Sonia">
                        <contenido url="www.contenido.es/id=P0001/nacional"></contenido>
                    </articulo>
                </seccion>
                <seccion tipo_sec="internacional">
                    <articulo autor="Jana">
                        <contenido url="www.contenido.es/id=P0001/internaciona"></contenido>
                    </articulo>
                </seccion>
            </secciones>
            <indice>
                <![CDATA[
                    Inicio.............1
                    Final..............2
                ]]>
            </indice>
            <contenido url="www.contenido.es/id=P0001"></contenido>
        </periodico>

    </documentos>  

</biblioteca>
