=== alfonsoroca/lmsgi-actividad2/XSD_biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="documento">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded"> <!-- Definimos el orden de los elementos de tal manera que no importe el orden en que aparecen, ni su ocurrencia-->
                <!-- Definimos la estructura de la etiqueta libro y la hacemos opcional por si el XML no tuviese etiquetas libro -->
                <xs:element name="libro" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo_lib" type="xs:string" />
                            <xs:element name="capitulos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="capitulo" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulo_cap" type="xs:string" />
                                                    <xs:element name="contenido_cap">
                                                        <xs:complexType>
                                                            <!-- Validamos el contenido del atributo -->
                                                            <xs:attribute name="url" use="required">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:anyURI">
                                                                        <xs:pattern value="(http|https)://www\..*" />
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <!-- Validamos el contenido del atributo -->
                                                <xs:attribute name="pags_cap" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="1" />
                                                            <xs:maxInclusive value="9999" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="indice_lib" type="xs:string" />
                            <xs:element name="sinopsis_lib" type="xs:string" />
                        </xs:sequence>
                        <!-- Validamos el contenido del atributo -->
                        <xs:attribute name="id_lib" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:ID">
                                    <xs:pattern value="L[0-9]{4}" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <!-- Validamos el contenido del atributo -->
                        <xs:attribute name="tipo_clase_lib" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="novela" />
                                    <xs:enumeration value="infantil" />
                                    <xs:enumeration value="didactico" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <!-- Validamos el contenido del atributo -->
                        <xs:attribute name="pags_lib" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1" />
                                    <xs:maxInclusive value="9999" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>

                <!-- Definimos la estructura de la etiqueta revista y la hacemos opcional por si el XML no tuviese etiquetas revista -->
                <xs:element name="revista" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo_rev" type="xs:string" />
                            <xs:element name="numero" type="xs:integer" />
                            <xs:element name="indice_rev" type="xs:string"/>                            
                            <xs:element name="seccion_rev" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="contenido_sec_rev">
                                            <xs:complexType>
                                                <!-- Validamos el contenido del atributo -->
                                                <xs:attribute name="url" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:anyURI">
                                                            <xs:pattern value="(http|https)://www\..*" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <!-- Validamos el contenido del atributo -->
                                    <xs:attribute name="pags_sec" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="1" />
                                                <xs:maxInclusive value="9999" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="contenido_rev">
                                <xs:complexType>
                                    <!-- Validamos el contenido del atributo -->
                                    <xs:attribute name="url" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:anyURI">
                                                <xs:pattern value="(http|https)://www\..*" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <!-- Validamos el contenido del atributo -->
                        <xs:attribute name="id_rev" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:ID">
                                    <xs:pattern value="R[0-9]{4}" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <!-- Validamos el contenido del atributo -->
                        <xs:attribute name="tipo_clase_rev" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="informatica" />
                                    <xs:enumeration value="corazon" />
                                    <xs:enumeration value="coches" />
                                    <xs:enumeration value="investigacion" />
                                    <xs:enumeration value="otras" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <!-- Validamos el contenido del atributo -->
                        <xs:attribute name="pags_rev" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1" />
                                    <xs:maxInclusive value="9999" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>

                <!-- Definimos la estructura de la etiqueta periodico y la hacemos opcional por si el XML no tuviese etiquetas periodico -->
                <xs:element name="periodico" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="seccion_per" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>                                                   
                                        <xs:element name="articulo" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="autor" type="xs:string" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="tipo_seccion_per" use="required">
                                        <!-- Validamos el contenido del atributo -->
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="economica" />
                                                <xs:enumeration value="opinion" />
                                                <xs:enumeration value="deportes" />
                                                <xs:enumeration value="nacional" />
                                                <xs:enumeration value="internacional" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="indice_per" type="xs:string" />
                            <xs:element name="contenido_per">
                                <xs:complexType>
                                    <!-- Validamos el contenido del atributo -->
                                    <xs:attribute name="url" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:anyURI">
                                                <xs:pattern value="(http|https)://www\..*" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id_per" use="required">
                            <!-- Validamos el contenido del atributo -->
                            <xs:simpleType>
                                <xs:restriction base="xs:ID">                                    
                                    <xs:pattern value="P[0-9]{4}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="tipo_clase_per" use="required">
                            <!-- Validamos el contenido del atributo -->
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="nacional" />
                                    <xs:enumeration value="internacional" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="fecha_publicacion" type="xs:date" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alfonsoroca/lmsgi-actividad2/XSD_bibilioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<documento xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XSD_biblioteca.xsd">

    <!-- Libros******************************************************************* -->

    <libro id_lib="L1234" tipo_clase_lib="novela" pags_lib="750">
        <titulo_lib>La Biblia</titulo_lib>
        <capitulos>
            <capitulo pags_cap="185">
                <titulo_cap>Génesis</titulo_cap>
                <contenido_cap url="http://www.l1234.es/genesis" />
            </capitulo>
            <capitulo pags_cap="100">
                <titulo_cap>Éxodo</titulo_cap>
                <contenido_cap url="http://www.l1234.es/exodo" />
            </capitulo>
        </capitulos>
        <indice_lib>1 Comienzo, 2 Continuación, 3 Final</indice_lib>
        <sinopsis_lib>La historia del origen del hombre desde un punto de vista religioso</sinopsis_lib>
    </libro>

    <!-- Revistas***************************************************************** -->

    <revista id_rev="R1234" tipo_clase_rev="informatica" pags_rev="125">
        <titulo_rev>Micromanía</titulo_rev>
        <numero>14</numero>
        <indice_rev>1 Mejores juegos, 2 Pokes, 3 Entrevistas</indice_rev>
        <seccion_rev pags_sec="18">
                <contenido_sec_rev url="http://www.r1234.es/mejoresjuegos" />
        </seccion_rev>
        <seccion_rev pags_sec="13">
                <contenido_sec_rev url="http://www.r1234.es/pokes" />
        </seccion_rev>
        <contenido_rev url="http://www.r1234.es" />
    </revista>

    <!-- Periódicos*************************************************************** -->

    <periodico id_per="P1234" tipo_clase_per="nacional" fecha_publicacion="2021-05-11">        
        <seccion_per tipo_seccion_per="deportes">                
            <articulo autor="Paco Roncero">Messi deja el Barsa</articulo>
            <articulo autor="Lamas">Madrid Campeón</articulo>                
        </seccion_per>
        <seccion_per tipo_seccion_per="economica">                
                <articulo autor="Montero">España en quiebra</articulo>
                <articulo autor="Escribá">Sin pensiones</articulo>                
        </seccion_per>
        <indice_per>Deportes, Economía, Anuncios</indice_per>
        <contenido_per url="http://www.p1234.es" />
    </periodico>

</documento>
