=== alfonsoroca/lmsgi-actividad2/cesar/DTD_biblioteca.dtd
<!ELEMENT biblioteca (libros, revista, periodicos)>

<!-- ====================================Definicion de Elementos Libro ============================-->
<!ELEMENT libros (titulo_libro, capitulo+, indice_libro, sinopsis_libro)>
<!ELEMENT titulo_libro (#PCDATA)>
<!ELEMENT capitulo (titulo_capitulo, contenido_capitulo)>
<!ELEMENT titulo_capitulo (#PCDATA)>
<!ELEMENT contenido_capitulo EMPTY>
<!ELEMENT indice_libro (#PCDATA)>
<!ELEMENT sinopsis_libro (#PCDATA)>
<!-- Definicion de Atributos Libros-->
<!ATTLIST libros id (L) #REQUIRED>
<!ATTLIST libros paginas_libro CDATA #REQUIRED>
<!ATTLIST libros tipo_libro (novela | infantil | didactico) #REQUIRED>
<!ATTLIST capitulo paginas_capitulo CDATA #REQUIRED>
<!ATTLIST contenido_capitulo url CDATA #REQUIRED>

<!-- ====================================Definicion de Elementos Revista ============================-->
<!ELEMENT revista (titulo_revista, numero_revista, indice_revista, contenido_revista)>
<!ELEMENT titulo_revista (#PCDATA)>
<!ELEMENT numero_revista (#PCDATA)>
<!ELEMENT indice_revista (seccion_revista+)>
<!ELEMENT seccion_revista (contenido_seccion_revista)>
<!ELEMENT contenido_seccion_revista EMPTY>
<!ELEMENT contenido_revista EMPTY>
<!-- Definicion de Atributos Revistas-->
<!ATTLIST revista id (R) #REQUIRED>
<!ATTLIST revista tipo_revista (informatica | corazon | coches | investigacion | otras) #REQUIRED>
<!ATTLIST revista paginas_revista CDATA #REQUIRED>
<!ATTLIST seccion_revista paginas_seccion CDATA #REQUIRED>
<!ATTLIST contenido_seccion_revista url CDATA #REQUIRED>
<!ATTLIST contenido_revista url CDATA #REQUIRED>

<!-- =====================================Definicion de Elementos Periodico =============================-->
<!ELEMENT periodicos (secciones_periodico, indice_periodico, contenido_periodico)>
<!ELEMENT secciones_periodico (seccion_periodico+)>
<!ELEMENT seccion_periodico (articulos+)>
<!ELEMENT articulos (#PCDATA)>
<!ELEMENT indice_periodico (#PCDATA)>
<!ELEMENT contenido_periodico (#PCDATA)>
<!-- Definicion de Atributos Periodicos-->
<!ATTLIST periodicos id (P) #REQUIRED>
<!ATTLIST periodicos tipo_periodico (nacional | internacional) #REQUIRED>
<!ATTLIST periodicos fecha CDATA #REQUIRED>
<!ATTLIST secciones_periodico tipo_seccion (economica | opinion | deportes | nacional | internacional) #REQUIRED>
<!ATTLIST articulos autor CDATA #REQUIRED>

=== alfonsoroca/lmsgi-actividad2/cesar/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "DTD_biblioteca.dtd">
<biblioteca>
    <!-- Estructura Libro -->
    <libros id="L1232" paginas_libro="245" tipo_libro="novela">
        <titulo_libro> </titulo_libro>
        <capitulo paginas_capitulo="23">
            <titulo_capitulo></titulo_capitulo>
            <contenido_capitulo url="www.libros.es"/>
        </capitulo>
        <capitulo paginas_capitulo="18">
            <titulo_capitulo></titulo_capitulo>
            <contenido_capitulo url="www.libros.es"/>
        </capitulo>
        <indice_libro></indice_libro>
        <sinopsis_libro></sinopsis_libro>
    </libros>

    <!-- Estructura Revista -->
    <revista id="R5421" tipo_revista="coches" paginas_revista="9">
        <titulo_revista></titulo_revista>
        <numero_revista></numero_revista>
        <indice_revista>
            <seccion_revista paginas_seccion="5">
                <contenido_seccion_revista url="www.revistas-de-coches.es"/>
            </seccion_revista>
            <seccion_revista paginas_seccion="3">
                <contenido_seccion_revista url="www.revistas-de-coches.es"/>
            </seccion_revista>
        </indice_revista>
        <contenido_revista url="www.revistas-de-coches.es"/>
    </revista>

    <!-- Estructura Periodico -->
    <periodicos id="P2543" tipo_periodico="nacional" fecha="15/05/2021">
        <secciones_periodico tipo_seccion="deportes">
            <seccion_periodico>
                <articulos autor="cesar"></articulos>
                <articulos autor="jose luis"></articulos>
            </seccion_periodico>
        </secciones_periodico>
        <indice_periodico></indice_periodico>
        <contenido_periodico></contenido_periodico>
    </periodicos>
</biblioteca>
