=== alfonsoroca/lmsgi-actividad2/cesar/XSD_biblioteca.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">

    <element name="biblioteca2">
        <complexType>
            <choice minOccurs="0" maxOccurs="unbounded">          <!-- Estructura Libro -->
                <element name="libros" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="titulo_libro" type="string"/>
                            <element name="capitulo" maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                        <element name="titulo_capitulo" type="string"/>
                                        <element name="contenido_capitulo">
                                            <complexType>
                                                <attribute name="url"  use="required">
                                                    <simpleType>
                                                        <restriction base="anyURI">
                                                            <pattern value="http://www.*"/>
                                                        </restriction>
                                                    </simpleType>
                                                </attribute>
                                            </complexType>
                                        </element>
                                    </sequence>
                                <attribute name="paginas_capitulo" type="integer" use="required"></attribute>
                                </complexType>
                            </element>
                            <element name="indice_libro"></element>
                            <element name="sinopsis_libro"></element>
                        </sequence>
                        <attribute name="id"  use="required">
                            <simpleType>
                                <restriction base="ID">
                                    <pattern value="L[0-9]{4}"/>
                                </restriction>
                            </simpleType>
                        </attribute>
                        <attribute name="paginas_libro" type="integer" use="required"/>
                        <attribute name="tipo_libro" use="required" >
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="novela"/>
                                    <enumeration value="infantil"/>
                                    <enumeration value="didactico"/>
                                </restriction>
                            </simpleType>
                        </attribute>
                    </complexType>
                </element>
                            <!-- Estructura Revista -->
                <element name="revista" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="titulo_revista"></element>
                            <element name="numero_revista"></element>
                            <element name="indice_revista">
                                <complexType>
                                    <sequence>
                                        <element name="seccion_revista"  maxOccurs="unbounded">
                                            <complexType>
                                                <sequence>
                                                    <element name="contenido_seccion_revista">
                                                        <complexType>
                                                            <attribute name="url"  use="required">
                                                                <simpleType>
                                                                    <restriction base="anyURI">
                                                                        <pattern value="http://www.*"></pattern>
                                                                    </restriction>
                                                                </simpleType>
                                                            </attribute>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                                <attribute name="paginas_seccion" type="integer" use="required" />
                                            </complexType>
                                        </element>
                                    </sequence>         
                                </complexType>
                            </element>
                            <element name="contenido_revista">
                                <complexType>
                                    <attribute name="url"  use="required">
                                        <simpleType>
                                            <restriction base="anyURI">
                                                <pattern value="http://www.*"/>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                </complexType>
                            </element>
                        </sequence>
                    <attribute name="id" use="required">
                        <simpleType>
                            <restriction base="ID">
                                <pattern value="R[0-9]{4}"/>
                            </restriction>
                        </simpleType>
                    </attribute>
                    <attribute name="tipo_revista" use="required" >
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="informatica"/>
                                <enumeration value="corazon"/>
                                <enumeration value="coches"/>
                                <enumeration value="investigacion"/>
                                <enumeration value="otras"/>
                            </restriction>
                        </simpleType>
                    </attribute>
                    <attribute name="paginas_revista" use="required"></attribute>
                    </complexType>
                </element>

                            <!-- Estructura Periodico -->
                <element name="periodicos" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="secciones_periodico">
                                <complexType>
                                    <sequence>                                       
                                        <element name="articulos"  maxOccurs="unbounded">
                                            <complexType>
                                                <simpleContent>
                                                    <extension base="string">
                                                        <attribute name="autor" type="string" use="required"/>
                                                    </extension>
                                                </simpleContent>                                                     
                                            </complexType>
                                        </element>           
                                    </sequence>
                                    <attribute name="tipo_seccion" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <enumeration value="economia"></enumeration>
                                                <enumeration value="opinion"></enumeration>
                                                <enumeration value="deportes"></enumeration>
                                                <enumeration value="nacional"></enumeration>
                                                <enumeration value="internacional"></enumeration>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                </complexType>
                            </element>
                            <element name="indice_periodico"></element>
                            <element name="contenido_periodico">
                                <complexType>
                                    <attribute name="url" use="required">
                                        <simpleType>
                                            <restriction base="anyURI">
                                                <pattern value="http://www.*"/>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="id" use="required">
                            <simpleType>
                                <restriction base="ID">
                                    <pattern value="P[0-9]{4}"/>
                                </restriction>
                            </simpleType>
                        </attribute>
                        <attribute name="tipo_periodico" use="required">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="nacional"></enumeration>
                                    <enumeration value="internacional"></enumeration>
                                </restriction>
                            </simpleType>
                        </attribute>
                        <attribute name="fecha" type="date" use="required"></attribute>
                    </complexType>
                </element>
            </choice>          
        </complexType>
    </element>
</schema>

=== alfonsoroca/lmsgi-actividad2/cesar/biblioteca2.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca2  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation= "XSD_biblioteca.xsd">
    <!-- Estructura Libro -->
    <libros id="L1234" paginas_libro="245" tipo_libro="novela">
        <titulo_libro>Don Quijote </titulo_libro>
        <capitulo paginas_capitulo="23">
            <titulo_capitulo>caapitulo 1</titulo_capitulo>
            <contenido_capitulo url="www.libros.es"/>
        </capitulo>
        <capitulo paginas_capitulo="18">
            <titulo_capitulo>capitulo 2</titulo_capitulo>
            <contenido_capitulo url="www.libros.es"/>
        </capitulo>
        <indice_libro> Aqui se encuentra el indice del libro</indice_libro>
        <sinopsis_libro>Aqui se encuentra la sinopsis del libro</sinopsis_libro>
    </libros>

    <!-- Estructura Revista -->
    <revista id="R1234" tipo_revista="coches" paginas_revista="9">
        <titulo_revista>coches.net</titulo_revista>
        <numero_revista>23</numero_revista>
        <indice_revista>
            <seccion_revista paginas_seccion="5">
                <contenido_seccion_revista url="www.revistas-de-coches.es"/>
            </seccion_revista>
            <seccion_revista paginas_seccion="3">
                <contenido_seccion_revista url="www.revistas-de-coches.es"/>
            </seccion_revista>
        </indice_revista>
        <contenido_revista url="www.revistas-de-coches.es"/>
    </revista>

    <!-- Estructura Periodico -->
    <periodicos id="P1234" tipo_periodico="nacional" fecha="2021-05-15">
        <secciones_periodico tipo_seccion="deportes">
            <seccion_periodico>
                <articulos autor="cesar"></articulos>
                <articulos autor="jose luis"></articulos>
            </seccion_periodico>
        </secciones_periodico>
        <indice_periodico>Aqui se encuentra el indice del periodico</indice_periodico>
        <contenido_periodico url="www.periodico.es"></contenido_periodico>
    </periodicos>
</biblioteca2>
